bert_scorer:
  (): bert_score.BERTScorer
  lang: "en"
  rescale_with_baseline: True
  model_type: "bert-base-uncased"

bleu_scorer:
  (): sacrebleu.BLEU
  trg_lang: ""
  effective_order: True

model: !import:flan-t5-base-model model_configs.yml
tokenizer: !import:flan-t5-base-tokenizer model_configs.yml

detectors:
  - (): Todd.MahalanobisScorer
    layers: [-1]
  - (): Todd.CosineProjectionScorer
    layers: [-1]

experiment_args:
  (): scripts.configs.wrapper.ExperimentArgs
  output_dir: "output/"
  num_workers: 4
  num_return_sequences: 4
  seed: 42
  append: false
  device: "cuda"
  batch_size: 64
  # validation_size: 20
  # test_size: 20
