bert:
  (): scripts.configs.wrapper.BERTScorerWrapper
  lang: "en"
  rescale_with_baseline: True
  model_type: "bert-base-uncased"

bleu:
  (): scripts.configs.wrapper.BLEUWrapper
  trg_lang: ""
  effective_order: True


model:
  (): scripts.configs.wrapper.AutoModelForSeq2SeqLMWrapper
  pretrained_model_name_or_path: "t5-base"

tokenizer:
  (): scripts.configs.wrapper.AutoTokenizerWrapper
  pretrained_model_name_or_path: "t5-base"
